SceneGraph Class Reference
#include <SceneGraph.h>
Detailed Description
This class is the scene graph.
Definition at line 24 of file SceneGraph.h.
Public Member Functions
SceneGraph (void)
Default constructor.
~SceneGraph (void)
Default destructor.
void addRootNode (boost::shared_ptr< SceneGraphNode > rootNode)
Parameters:
rootNode The node that will become the node of the scene graph
void addNode (boost::shared_ptr< SceneGraphNode > parentNode, boost::shared_ptr< SceneGraphNode > childNode)
Parameters:
parentNode The parent node already in the scene graph
boost::shared_ptr< SceneGraphNode > getNode (vertex_descriptor id)
Parameters:
id an index of which node to return
std::string listNodes (void)
Parameters:
outputStream an output stream to write a list of nodes in the graphs to
const graph_type getGraph (void)
Returns: a graph instance to be traversed by an algorithm
std::string getDotGraph (void)
Returns: a string containing the graph in graphviz dot format
Constructor & Destructor Documentation
SceneGraph::SceneGraph (void)
Default constructor.
Definition at line 7 of file SceneGraph.cpp.
SceneGraph::~SceneGraph (void)
Default destructor.
Definition at line 12 of file SceneGraph.cpp.
Member Function Documentation
void SceneGraph::addRootNode (boost::shared_ptr< SceneGraphNode > rootNode)
Parameters:
rootNode The node that will become the node of the scene graph
Warning: there can only be one root node add a root node
Definition at line 16 of file SceneGraph.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
void SceneGraph::addNode (boost::shared_ptr< SceneGraphNode > parentNode, boost::shared_ptr< SceneGraphNode > childNode)
Parameters:
parentNode The parent node already in the scene graph
Parameters:
childNode The child
Warning: the parent node must be in the graph already and the child node can not be add a child node to the graph with a specific parent
Definition at line 33 of file SceneGraph.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
boost::shared_ptr< SceneGraphNode > SceneGraph::getNode (vertex_descriptor id)
Parameters:
id an index of which node to return
Returns: the node indicated by the index
Definition at line 54 of file SceneGraph.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
std::string SceneGraph::listNodes (void)
Parameters:
outputStream an output stream to write a list of nodes in the graphs to
Definition at line 59 of file SceneGraph.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
const graph_type SceneGraph::getGraph (void)
Returns: a graph instance to be traversed by an algorithm
Definition at line 72 of file SceneGraph.cpp.
std::string SceneGraph::getDotGraph (void)
Returns: a string containing the graph in graphviz dot format
Definition at line 79 of file SceneGraph.cpp.
The documentation for this class was generated from the following files:
SceneGraph.h
SceneGraph.cpp