SceneGraphTest.cpp File Reference
#include `stdafx.h`
#include <boost/test/auto_unit_test.hpp>
#include `GroupNode.h`
#include `SceneGraph.h`
#include <boost/shared_ptr.hpp>
#include <iostream>
#include `ListGraphVisitor.h`
Defines
#define BOOST_AUTO_TEST_MAIN
Functions
BOOST_AUTO_TEST_CASE (scene_graph_stream_operator_test)
BOOST_AUTO_TEST_CASE (scene_graph_add_root_node_test)
BOOST_AUTO_TEST_CASE (scene_graph_add_node_test)
BOOST_AUTO_TEST_CASE (print_vertices_test)
BOOST_AUTO_TEST_CASE (pretty_print_vertices_test)
BOOST_AUTO_TEST_CASE (write_dot_test)
Define Documentation
#define BOOST_AUTO_TEST_MAIN
Definition at line 5 of file SceneGraphTest.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (scene_graph_stream_operator_test)
Definition at line 14 of file SceneGraphTest.cpp.
BOOST_AUTO_TEST_CASE (scene_graph_add_root_node_test)
Definition at line 24 of file SceneGraphTest.cpp.
References SceneGraph::addRootNode(), and SceneGraph::getNode().
BOOST_AUTO_TEST_CASE (scene_graph_add_node_test)
Definition at line 34 of file SceneGraphTest.cpp.
References SceneGraph::addNode(), and SceneGraph::addRootNode().
BOOST_AUTO_TEST_CASE (print_vertices_test)
Definition at line 46 of file SceneGraphTest.cpp.
References SceneGraph::addNode(), SceneGraph::addRootNode(), and SceneGraph::listNodes().
BOOST_AUTO_TEST_CASE (pretty_print_vertices_test)
Definition at line 85 of file SceneGraphTest.cpp.
References ListGraphVisitor::getGraphList().
BOOST_AUTO_TEST_CASE (write_dot_test)
Definition at line 122 of file SceneGraphTest.cpp.